Hello, Blockstack Vue
blockstack/blockstack-app-generator pull request #54
Opened 2019-06-19 21:46 UTC by Sahana-Srinivasan

Used blockstack-todos Vue packaging and modified Profile/Signed components from [PR 15](https://github.com/blockstack/blockstack-app-generator/pull/15) to make a Hello, Blockstack app generator for Vue.

2019-06-19 21:51 UTC, Sahana-Srinivasan commented
Updated the Profile/SignIn components to reflect new versions of Blockstack with slightly different sign-in process. Combined with the updated packaging of blockstack-todos for an updated "Hello, Blockstack" Vue app generator in [this pull request](https://github.com/blockstack/blockstack-app-generator/pull/54).

2019-07-01 19:10 UTC, hstove commented
The git diff is hard to parse. It seems like some React and Webpack code is also altered? Is this PR built on top of a different PR that isn't merged to master, yet?

2019-07-01 19:20 UTC, Sahana-Srinivasan commented
> The git diff is hard to parse. It seems like some React and Webpack code is also altered? Is this PR built on top of a different PR that isn't merged to master, yet?

This encapsulates the React generator updates made in PR 50, yeah. The general app generator/Webpack generator received minor updates just to make the Hello Blockstack page blue and look more similar to blockstack.org. Updated the PR comment.

2019-07-01 20:41 UTC, zone117x commented
Looks like this needs the master branch merged in (or rebased on top of the master branch)

2019-07-02 20:04 UTC, Sahana-Srinivasan commented
> The git diff is hard to parse. It seems like some React and Webpack code is also altered? Is this PR built on top of a different PR that isn't merged to master, yet?

@hstove Yeah, it modifies the blockstack logos/color for all the generators, improves the packaging for the React generator, creates a more robust test script, and adds the Vue generator. Also, Matt and I went through the merge conflicts so the diff should be more coherent now.

2019-07-15 14:33 UTC, Sahana-Srinivasan commented
@zone117x Does this look good to go?

2019-07-22 18:59 UTC, zone117x commented on app/templates/_package.json
> +    "test": "echo works"
This should probably be changed to something like `echo "TODO: write tests"`

2019-07-22 19:11 UTC, zone117x commented on vue/templates/docker-compose.yaml
> +version: '2'
Is this file being used anywhere or still work?

2019-07-22 19:13 UTC, zone117x commented on vue/templates/browserslistrc
> +> 1%
Should this be moved into the `_package.json` like the other generators?
(I know this this Vue template code is from another contributor's older PR)

2019-07-22 19:21 UTC, zone117x commented on vue/templates/_package.json
> +    "test:unit": "vue-cli-service test:unit --coverage --coverageReporters=lcov",
When running `npm run test:unit` I'm getting an error:
```
> vue-cli-service test:unit --coverage --coverageReporters=lcov

Error: Could not resolve a module for a custom reporter.
  Module name: jest-junit
    at options.reporters.reporters.map.reporterConfig (/Users/matt/Projects/blockstack-app-generator/.vue-gen-test/node_modules/jest-config/build/normalize.js:419:15)
    at Array.map (<anonymous>)
    at normalizeReporters (/Users/matt/Projects/blockstack-app-generator/.vue-gen-test/node_modules/jest-config/build/normalize.js:397:33)
    at normalize (/Users/matt/Projects/blockstack-app-generator/.vue-gen-test/node_modules/jest-config/build/normalize.js:494:5)
    at readConfig (/Users/matt/Projects/blockstack-app-generator/.vue-gen-test/node_modules/jest-config/build/index.js:184:68)
    at getConfigs (/Users/matt/Projects/blockstack-app-generator/.vue-gen-test/node_modules/jest/node_modules/jest-cli/build/cli/index.js:473:77)
    at /Users/matt/Projects/blockstack-app-generator/.vue-gen-test/node_modules/jest/node_modules/jest-cli/build/cli/index.js:251:23
    at Generator.next (<anonymous>)
    at step (/Users/matt/Projects/blockstack-app-generator/.vue-gen-test/node_modules/jest/node_modules/jest-cli/build/cli/index.js:206:30)
    at /Users/matt/Projects/blockstack-app-generator/.vue-gen-test/node_modules/jest/node_modules/jest-cli/build/cli/index.js:225:14
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bs-todo@6.0.1 test:unit: `vue-cli-service test:unit --coverage --coverageReporters=lcov`
npm ERR! Exit status 1
```

I'm not really familiar with Vue or what code/tests this is trying to exercise -- should we fix this or remove it?

2019-07-22 19:27 UTC, zone117x commented on react/templates/_package.json
> +    "build": "react-scripts build",
Getting some minor linting warnings when building:
```
Compiled with warnings.

./src/App.js
  Line 14:  Useless constructor  no-useless-constructor

./src/index.js
  Line 1:  'Component' is defined but never used  no-unused-vars
  Line 7:   'bootstrap' is defined but never used  no-unused-vars
  Line 8:   'style' is defined but never used      no-unused-vars

./src/Signin.js
  Line 4:  Useless constructor  no-useless-constructor
```

2019-07-22 19:32 UTC, zone117x commented on app/index.js
>  var yosay = require('yosay');
I'm tempted to say we nuke this template and replace it with either the `react` or `webpack` template. Both of those templates generated more concise and clear app scaffolding than this one. Probably something that should be done in a later PR though.
@moxiegirl @yknl thoughts?

2019-07-22 19:35 UTC, zone117x requested changes
Tested all the generated apps, and all working for me on Chrome. The new theming looks great!
Left a few comments & questions about minor stuff. Other than addressing those, this PR looks good to me!

2019-07-22 20:45 UTC, yknl requested changes
Nice work @Sahana-Srinivasan. The updated UI looks great. Just a minor change in addition to what Matt added.

2019-07-22 20:45 UTC, yknl commented on react/templates/_package.json
> +    "blockstack": "^19.2.1",
We can update this to 19.2.2 now.

2019-07-30 14:36 UTC, yknl approved these changes
LGTM

2019-07-30 14:43 UTC, zone117x approved these changes
LGTM. Great job @Sahana-Srinivasan !

2019-07-30 14:57 UTC, merged